<?php
include 'config/database.php';
echo "<pre style='font-family:monospace;font-size:13px;'>";

// -- 20 BMW CARS: M Series (7), i Series (7), X Series (6) --
$cars = [

    // ========== M SERIES (7) ==========
    [
        'name' => 'BMW M2 Competition',
        'series' => 'M Series',
        'price' => 8500000,
        'body_type' => 'Coupe',
        'transmission' => 'Automatic',
        'fuel_type' => 'Petrol',
        'year' => 2024,
        'engine_cc' => '2993 cc',
        'power_hp' => '460 hp',
        'mileage' => '9 kmpl',
        'seats' => 4,
        'description' => 'The BMW M2 Competition is a high-performance compact coupe featuring a twin-turbocharged inline-6 engine, M-tuned suspension, and iconic M brakes. Pure driving excitement in a compact body.',
        'is_featured' => 1,
        'image' => 'https://images.unsplash.com/photo-1617814076229-f8e8e3e8a7e1?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW M3 Competition',
        'series' => 'M Series',
        'price' => 11900000,
        'body_type' => 'Sedan',
        'transmission' => 'Automatic',
        'fuel_type' => 'Petrol',
        'year' => 2024,
        'engine_cc' => '2993 cc',
        'power_hp' => '503 hp',
        'mileage' => '10 kmpl',
        'seats' => 5,
        'description' => 'The BMW M3 Competition Sedan combines everyday usability with race-track performance. With 503 hp, M xDrive AWD, and a carbon fibre interior, this is the ultimate sports sedan.',
        'is_featured' => 1,
        'image' => 'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW M4 Competition',
        'series' => 'M Series',
        'price' => 13900000,
        'body_type' => 'Coupe',
        'transmission' => 'Automatic',
        'fuel_type' => 'Petrol',
        'year' => 2024,
        'engine_cc' => '2993 cc',
        'power_hp' => '503 hp',
        'mileage' => '10 kmpl',
        'seats' => 4,
        'description' => 'The BMW M4 Competition Coupe is an icon of motorsport heritage. Twin-turbocharged S58 engine, M-specific aerodynamics, and track-tuned chassis make every drive a spectacle.',
        'is_featured' => 1,
        'image' => 'https://images.unsplash.com/photo-1617814076369-c98dd26a5fe2?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW M5 Competition',
        'series' => 'M Series',
        'price' => 18900000,
        'body_type' => 'Sedan',
        'transmission' => 'Automatic',
        'fuel_type' => 'Petrol',
        'year' => 2024,
        'engine_cc' => '4395 cc',
        'power_hp' => '627 hp',
        'mileage' => '8 kmpl',
        'seats' => 5,
        'description' => 'The BMW M5 Competition is the most powerful M5 ever made. A hand-built V8 twin-turbo, M xDrive, active M differential – this is a super saloon that devours circuits.',
        'is_featured' => 1,
        'image' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW M8 Gran Coupe',
        'series' => 'M Series',
        'price' => 26500000,
        'body_type' => 'Gran Coupe',
        'transmission' => 'Automatic',
        'fuel_type' => 'Petrol',
        'year' => 2024,
        'engine_cc' => '4395 cc',
        'power_hp' => '617 hp',
        'mileage' => '8 kmpl',
        'seats' => 4,
        'description' => 'The BMW M8 Gran Coupé blends breathtaking style with extreme performance. A 617 hp V8 engine, adaptive M suspension, and opulent interior make it the pinnacle of the M family.',
        'is_featured' => 1,
        'image' => 'https://images.unsplash.com/photo-1617814076229-f8e8e3e8a7e1?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW X3 M Competition',
        'series' => 'M Series',
        'price' => 12800000,
        'body_type' => 'SUV',
        'transmission' => 'Automatic',
        'fuel_type' => 'Petrol',
        'year' => 2024,
        'engine_cc' => '2993 cc',
        'power_hp' => '503 hp',
        'mileage' => '9 kmpl',
        'seats' => 5,
        'description' => 'The BMW X3 M Competition fuses the practicality of a premium SUV with pure M performance. S58 power, M Sport exhaust, and M-specific xDrive deliver a thrilling driving experience.',
        'is_featured' => 0,
        'image' => 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW X5 M Competition',
        'series' => 'M Series',
        'price' => 21500000,
        'body_type' => 'SUV',
        'transmission' => 'Automatic',
        'fuel_type' => 'Petrol',
        'year' => 2024,
        'engine_cc' => '4395 cc',
        'power_hp' => '617 hp',
        'mileage' => '7 kmpl',
        'seats' => 5,
        'description' => 'The BMW X5 M Competition is the ultimate performance SAV. Blistering V8 performance, M Sport exhaust, M compound brakes, and a luxurious cabin make it unstoppable on road or track.',
        'is_featured' => 1,
        'image' => 'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=900&q=80',
    ],

    // ========== i SERIES (7) ==========
    [
        'name' => 'BMW i3',
        'series' => 'i Series',
        'price' => 4890000,
        'body_type' => 'Hatchback',
        'transmission' => 'Automatic',
        'fuel_type' => 'Electric',
        'year' => 2023,
        'engine_cc' => 'Electric Motor',
        'power_hp' => '170 hp',
        'mileage' => '300 km range',
        'seats' => 4,
        'description' => 'The BMW i3 is a pioneering city electric vehicle with sustainable construction. Its advanced eDrive system, carbon-fibre reinforced body, and urban-focused design set the standard for EVs.',
        'is_featured' => 0,
        'image' => 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW i4 eDrive40',
        'series' => 'i Series',
        'price' => 7790000,
        'body_type' => 'Gran Coupe',
        'transmission' => 'Automatic',
        'fuel_type' => 'Electric',
        'year' => 2024,
        'engine_cc' => 'Electric Motor',
        'power_hp' => '340 hp',
        'mileage' => '590 km range',
        'seats' => 5,
        'description' => 'The BMW i4 eDrive40 is a stunning electric Gran Coupé with a 590 km range. Combining sporty handling with zero-emission luxury, it sets a new benchmark for electric performance.',
        'is_featured' => 1,
        'image' => 'https://images.unsplash.com/photo-1617814076229-f8e8e3e8a7e1?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW i4 M50',
        'series' => 'i Series',
        'price' => 9500000,
        'body_type' => 'Gran Coupe',
        'transmission' => 'Automatic',
        'fuel_type' => 'Electric',
        'year' => 2024,
        'engine_cc' => 'Dual Electric Motor',
        'power_hp' => '544 hp',
        'mileage' => '510 km range',
        'seats' => 5,
        'description' => 'The BMW i4 M50 is the first fully electric M car. With 544 hp, dual motors, and M Sport suspension, it accelerates 0–100 km/h in just 3.9 seconds while delivering 510 km of range.',
        'is_featured' => 1,
        'image' => 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW i5 eDrive40',
        'series' => 'i Series',
        'price' => 9600000,
        'body_type' => 'Sedan',
        'transmission' => 'Automatic',
        'fuel_type' => 'Electric',
        'year' => 2024,
        'engine_cc' => 'Electric Motor',
        'power_hp' => '340 hp',
        'mileage' => '582 km range',
        'seats' => 5,
        'description' => 'The BMW i5 eDrive40 is a luxurious electric executive sedan. Elegantly designed, packed with driver assistance tech and offering up to 582 km of range – the future of the 5 Series.',
        'is_featured' => 0,
        'image' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW i7 xDrive60',
        'series' => 'i Series',
        'price' => 19500000,
        'body_type' => 'Sedan',
        'transmission' => 'Automatic',
        'fuel_type' => 'Electric',
        'year' => 2024,
        'engine_cc' => 'Dual Electric Motor',
        'power_hp' => '544 hp',
        'mileage' => '625 km range',
        'seats' => 5,
        'description' => 'The BMW i7 xDrive60 redefines electric luxury. Theatre Screen in the rear, a 625 km range, and a 31.3-inch 8K Display - this is the world\'s most advanced electric luxury limousine.',
        'is_featured' => 1,
        'image' => 'https://images.unsplash.com/photo-1556189250-72ba954cfc2b?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW iX xDrive50',
        'series' => 'i Series',
        'price' => 13900000,
        'body_type' => 'SUV',
        'transmission' => 'Automatic',
        'fuel_type' => 'Electric',
        'year' => 2024,
        'engine_cc' => 'Dual Electric Motor',
        'power_hp' => '523 hp',
        'mileage' => '630 km range',
        'seats' => 5,
        'description' => 'The BMW iX xDrive50 is a visionary electric SUV. Its sculpted design, panoramic Sky Lounge roof, and up to 630 km range make it the flagship of the BMW electric lineup.',
        'is_featured' => 1,
        'image' => 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW iX1 xDrive30',
        'series' => 'i Series',
        'price' => 6690000,
        'body_type' => 'SUV',
        'transmission' => 'Automatic',
        'fuel_type' => 'Electric',
        'year' => 2024,
        'engine_cc' => 'Dual Electric Motor',
        'power_hp' => '313 hp',
        'mileage' => '440 km range',
        'seats' => 5,
        'description' => 'The BMW iX1 xDrive30 brings electric joy to the compact SUV segment. With sporty looks, a premium cabin, and 440 km of real-world range, it is the entry point to BMW electric luxury.',
        'is_featured' => 0,
        'image' => 'https://images.unsplash.com/photo-1612825173281-9a193378527e?auto=format&fit=crop&w=900&q=80',
    ],

    // ========== X SERIES (6) ==========
    [
        'name' => 'BMW X1 sDrive18i',
        'series' => 'X Series',
        'price' => 4590000,
        'body_type' => 'SUV',
        'transmission' => 'Automatic',
        'fuel_type' => 'Petrol',
        'year' => 2024,
        'engine_cc' => '1499 cc',
        'power_hp' => '136 hp',
        'mileage' => '16 kmpl',
        'seats' => 5,
        'description' => 'The BMW X1 sDrive18i is the premium entry-level SAV. Featuring a bold new design, 10.7-inch touchscreen, and efficient TwinPower Turbo engine, it combines style with everyday practicality.',
        'is_featured' => 0,
        'image' => 'https://images.unsplash.com/photo-1612825173281-9a193378527e?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW X3 xDrive30i',
        'series' => 'X Series',
        'price' => 6990000,
        'body_type' => 'SUV',
        'transmission' => 'Automatic',
        'fuel_type' => 'Petrol',
        'year' => 2024,
        'engine_cc' => '1998 cc',
        'power_hp' => '258 hp',
        'mileage' => '13 kmpl',
        'seats' => 5,
        'description' => 'The BMW X3 xDrive30i is the definitive mid-size luxury SUV. Intelligent all-wheel drive, a dynamic chassis, a premium cabin with Curved Display – built for those who want it all.',
        'is_featured' => 1,
        'image' => 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW X5 xDrive40i',
        'series' => 'X Series',
        'price' => 9390000,
        'body_type' => 'SUV',
        'transmission' => 'Automatic',
        'fuel_type' => 'Petrol',
        'year' => 2024,
        'engine_cc' => '2998 cc',
        'power_hp' => '340 hp',
        'mileage' => '11 kmpl',
        'seats' => 7,
        'description' => 'The BMW X5 xDrive40i is the benchmark luxury SAV. Its commanding presence, powerful inline 6-cylinder engine, air suspension, and opulent interior make every journey extraordinary.',
        'is_featured' => 1,
        'image' => 'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW X6 M50i',
        'series' => 'X Series',
        'price' => 11990000,
        'body_type' => 'SUV Coupe',
        'transmission' => 'Automatic',
        'fuel_type' => 'Petrol',
        'year' => 2024,
        'engine_cc' => '4395 cc',
        'power_hp' => '530 hp',
        'mileage' => '9 kmpl',
        'seats' => 5,
        'description' => 'The BMW X6 M50i is the original Sports Activity Coupé, now more powerful than ever. V8 power, a sweeping roofline, and commanding road presence ensure it remains an icon of style and performance.',
        'is_featured' => 1,
        'image' => 'https://images.unsplash.com/photo-1617814076229-f8e8e3e8a7e1?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW X7 xDrive40i',
        'series' => 'X Series',
        'price' => 12900000,
        'body_type' => 'SUV',
        'transmission' => 'Automatic',
        'fuel_type' => 'Petrol',
        'year' => 2024,
        'engine_cc' => '2998 cc',
        'power_hp' => '340 hp',
        'mileage' => '10 kmpl',
        'seats' => 7,
        'description' => 'The BMW X7 xDrive40i is the pinnacle of luxury SAVs. Three-row seating for seven, a panoramic Sky Lounge sunroof, massive 23-inch wheels option, and crystal-clear Bowers & Wilkins sound system.',
        'is_featured' => 1,
        'image' => 'https://images.unsplash.com/photo-1556189250-72ba954cfc2b?auto=format&fit=crop&w=900&q=80',
    ],
    [
        'name' => 'BMW X4 xDrive30i',
        'series' => 'X Series',
        'price' => 7690000,
        'body_type' => 'SUV Coupe',
        'transmission' => 'Automatic',
        'fuel_type' => 'Petrol',
        'year' => 2024,
        'engine_cc' => '1998 cc',
        'power_hp' => '252 hp',
        'mileage' => '12 kmpl',
        'seats' => 5,
        'description' => 'The BMW X4 xDrive30i is where sport meets SAV coupé style. Its distinctive fastback silhouette, sporty interior, and all-wheel drive confidence make it one of the most eye-catching BMWs.',
        'is_featured' => 0,
        'image' => 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=900&q=80',
    ],
];

// ----- INSERT -----
$carStmt = $pdo->prepare("
    INSERT INTO cars (name, brand, price, body_type, transmission, fuel_type, year, engine_cc, power_hp, mileage, seats, description, is_featured)
    VALUES (?, 'BMW', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
");

$imgStmt = $pdo->prepare("
    INSERT INTO car_images (car_id, image_path, is_primary) VALUES (?, ?, 1)
");

$inserted = 0;
foreach ($cars as $car) {
    // Skip if car with same name already exists
    $exists = $pdo->prepare("SELECT id FROM cars WHERE name = ?");
    $exists->execute([$car['name']]);
    if ($exists->fetch()) {
        echo "⚠️  Skipped (already exists): {$car['name']}\n";
        continue;
    }

    $carStmt->execute([
        $car['name'],
        $car['price'],
        $car['body_type'],
        $car['transmission'],
        $car['fuel_type'],
        $car['year'],
        $car['engine_cc'],
        $car['power_hp'],
        $car['mileage'],
        $car['seats'],
        $car['description'],
        $car['is_featured'],
    ]);
    $carId = $pdo->lastInsertId();

    $imgStmt->execute([$carId, $car['image']]);

    echo "✅  Added: {$car['name']} (ID: $carId) – {$car['series']}\n";
    $inserted++;
}

echo "\n🎉  Done! $inserted cars added successfully.\n";
echo "</pre>";
?>
